# Generated by Django 3.2 on 2022-03-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_group_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='updated',
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
