# Generated by Django 3.2 on 2022-03-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20220311_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='connected_groups',
            field=models.ManyToManyField(blank=True, related_name='_account_group_connected_groups_+', to='account.Group'),
        ),
    ]
