# Generated by Django 3.2 on 2022-03-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_group_connected_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created',)},
        ),
    ]
