# Generated by Django 3.2 on 2022-03-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_alter_joinrequest_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinrequest',
            options={'ordering': ('-date',)},
        ),
    ]
