# Generated by Django 3.2 on 2022-03-11 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20220311_1422'),
        ('connection', '0003_alter_joinrequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_request', to='account.group'),
        ),
    ]
